[build]
  command = "cd frontend && npm install && npm run build"
  functions = "netlify/functions"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

